# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blackbook}
  s.version = "1.0.21"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rany Keddo", "Brian Cardarella"]
  s.date = %q{2009-09-30}
  s.description = %q{It does things. Like import contacts from EVERYWHERE.}
  s.email = %q{bcardarella@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGES.markdown",
     "Manifest.txt",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "debug_blackbook.rb",
     "init.rb",
     "lib/blackbook.rb",
     "lib/blackbook/exporter/base.rb",
     "lib/blackbook/exporter/vcf.rb",
     "lib/blackbook/exporter/xml.rb",
     "lib/blackbook/importer/aol.rb",
     "lib/blackbook/importer/base.rb",
     "lib/blackbook/importer/csv.rb",
     "lib/blackbook/importer/freenet.rb",
     "lib/blackbook/importer/gmail.rb",
     "lib/blackbook/importer/gmx.rb",
     "lib/blackbook/importer/hotmail.rb",
     "lib/blackbook/importer/page_scraper.rb",
     "lib/blackbook/importer/web.de.rb",
     "lib/blackbook/importer/yahoo.rb",
     "test/config/credentials.yml.example",
     "test/fixtures/aol_application_page.html",
     "test/fixtures/aol_bad_login_response_stage_3.html",
     "test/fixtures/aol_contacts.html",
     "test/fixtures/aol_login_response_stage_1.html",
     "test/fixtures/aol_login_response_stage_2.html",
     "test/fixtures/aol_login_response_stage_3.html",
     "test/fixtures/aol_login_response_stage_4.html",
     "test/fixtures/aol_login_response_stage_5.html",
     "test/fixtures/aol_new_contacts.html",
     "test/fixtures/gmail.csv",
     "test/fixtures/gmail_bad_login_response_stage_2.html",
     "test/fixtures/gmail_contacts.html",
     "test/fixtures/gmail_login_response_stage_1.html",
     "test/fixtures/gmail_login_response_stage_2.html",
     "test/fixtures/gmail_login_response_stage_2a.html",
     "test/fixtures/gmail_login_response_stage_3.html",
     "test/fixtures/gmail_redirect_body.html",
     "test/fixtures/hotmail_bad_login_response_stage_2.html",
     "test/fixtures/hotmail_contacts.html",
     "test/fixtures/hotmail_login_response_stage_1.html",
     "test/fixtures/hotmail_login_response_stage_2.html",
     "test/fixtures/hotmail_login_response_stage_3.html",
     "test/fixtures/hotmail_scrape_first_page.html",
     "test/fixtures/hotmail_scrape_response_stage_1.html",
     "test/fixtures/hotmail_scrape_response_stage_2.html",
     "test/fixtures/hotmail_scrape_response_stage_3.html",
     "test/fixtures/yahoo_bad_login_response_stage_2.html",
     "test/fixtures/yahoo_contacts.csv",
     "test/fixtures/yahoo_contacts_not_logged_in.html",
     "test/fixtures/yahoo_contacts_stage_1.html",
     "test/fixtures/yahoo_login_response_stage_1.html",
     "test/fixtures/yahoo_login_response_stage_2.html",
     "test/fixtures/yahoo_no_user_response_stage_2.html",
     "test/freenet_importer_test.rb",
     "test/gmx_importer_test.rb",
     "test/scripts/live_test.rb",
     "test/test_blackbook.rb",
     "test/test_blackbook_exporter_base.rb",
     "test/test_blackbook_exporter_vcf.rb",
     "test/test_blackbook_exporter_xml.rb",
     "test/test_blackbook_importer_aol.rb",
     "test/test_blackbook_importer_base.rb",
     "test/test_blackbook_importer_csv.rb",
     "test/test_blackbook_importer_gmail.rb",
     "test/test_blackbook_importer_hotmail.rb",
     "test/test_blackbook_importer_page_scraper.rb",
     "test/test_blackbook_importer_yahoo.rb",
     "test/test_helper.rb",
     "test/web.de_importer_test.rb",
     "updater.rb",
     "vendor/plugins/blackbook/lib/autotest/blackbook.rb",
     "vendor/plugins/blackbook/lib/autotest/discover.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/kojul/blackbook}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{It does things. Like import contacts from EVERYWHERE.}
  s.test_files = [
    "test/freenet_importer_test.rb",
     "test/gmx_importer_test.rb",
     "test/scripts/live_test.rb",
     "test/test_blackbook.rb",
     "test/test_blackbook_exporter_base.rb",
     "test/test_blackbook_exporter_vcf.rb",
     "test/test_blackbook_exporter_xml.rb",
     "test/test_blackbook_importer_aol.rb",
     "test/test_blackbook_importer_base.rb",
     "test/test_blackbook_importer_csv.rb",
     "test/test_blackbook_importer_gmail.rb",
     "test/test_blackbook_importer_hotmail.rb",
     "test/test_blackbook_importer_page_scraper.rb",
     "test/test_blackbook_importer_yahoo.rb",
     "test/test_helper.rb",
     "test/web.de_importer_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0.7.0"])
      s.add_runtime_dependency(%q<mechanize>, [">= 0.7.0"])
      s.add_runtime_dependency(%q<hoe>, [">= 1.5.0"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 1.2.0"])
    else
      s.add_dependency(%q<hpricot>, [">= 0.7.0"])
      s.add_dependency(%q<mechanize>, [">= 0.7.0"])
      s.add_dependency(%q<hoe>, [">= 1.5.0"])
      s.add_dependency(%q<fastercsv>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0.7.0"])
    s.add_dependency(%q<mechanize>, [">= 0.7.0"])
    s.add_dependency(%q<hoe>, [">= 1.5.0"])
    s.add_dependency(%q<fastercsv>, [">= 1.2.0"])
  end
end
